# OpenCV Tutorial

In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread(r'D:\hrutik\Wallpapers\DIP\4.jpg', 1)

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
#printing pizel value of specific location

px = img[150, 150]
print(px)

[127 159 178]


In [4]:
#we can also modify the pixel value

img[150, 150] = [255, 255, 255]
px = img[150, 150]
print(px)

[255 255 255]


### ROI - Region of Image 

In [5]:
roi = img[150:200, 150:200]
print(roi)

[[[255 255 255]
  [127 159 178]
  [128 158 177]
  ...
  [153 181 192]
  [154 182 193]
  [154 182 193]]

 [[127 159 178]
  [127 159 178]
  [128 158 177]
  ...
  [153 181 192]
  [154 182 193]
  [154 182 193]]

 [[126 159 175]
  [126 159 175]
  [128 158 175]
  ...
  [153 181 192]
  [153 181 192]
  [154 182 193]]

 ...

 [[118 153 173]
  [116 151 171]
  [121 156 176]
  ...
  [156 185 199]
  [157 187 198]
  [158 188 199]]

 [[120 153 173]
  [119 152 172]
  [123 156 176]
  ...
  [157 186 200]
  [157 187 198]
  [158 188 199]]

 [[120 153 173]
  [122 155 175]
  [123 156 176]
  ...
  [158 187 201]
  [159 189 200]
  [159 189 200]]]


In [6]:
# changing pixel value of a certain region in image

img[150:200, 150:200] = [255, 255, 255]

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#cut and paste roi

image_cut = img[200:400, 100:600]
img[0:200, 0:500] = image_cut

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Some more image functions

In [8]:
img_1 = cv2.imread(r'D:\hrutik\Wallpapers\DIP\31.jpg', 1)
img_2 = cv2.imread(r'D:\hrutik\Wallpapers\DIP\8.png', 1)

#add = img_1 + img_2
#this added the images by their pixel values
#suppose if the value are
# [100, 200, 200] + [100, 111, 90]
# gives us [200, 311, 290] and coverts it to [200, 255, 255]

add = cv2.add(img_1, img_2)

cv2.imshow('add', add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#adding both images through weighted

weighted = cv2.addWeighted(img_1, 0.7, img_2, 0.3, 0)
cv2.imshow('weighted', weighted)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#thresholding image

img_1 = cv2.imread(r'D:\hrutik\Wallpapers\DIP\31.jpg', 1)
img_2 = cv2.imread(r'D:\hrutik\Wallpapers\DIP\p3.png', 1)

rows, cols, channels = img_2.shape
roi = img_1[0:rows, 0:cols]       #getting in no of rows and cols of image2 

#converting it into grayscale image
img2gray = cv2.cvtColor(img_2, cv2.COLOR_BGR2GRAY)

#thresholding value
ret, mask = cv2.threshold(img2gray, 220, 255, cv2.THRESH_BINARY_INV)

cv2.imshow('mask', mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
#croping image and adding adding it on first image

img_1 = cv2.imread(r'D:\hrutik\Wallpapers\DIP\31.jpg', 1)
img_2 = cv2.imread(r'D:\hrutik\Wallpapers\DIP\p3.png', 1)

# gettin in image2 size
rows, cols, channels = img_2.shape
roi = img_1[0:rows, 0:cols]

img2gray = cv2.cvtColor(img_2, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray, 220, 255, cv2.THRESH_BINARY_INV)

#appling bitwise operation on image to create mask
mask_inv = cv2.bitwise_not(mask)

img1_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)
img2_fg = cv2.bitwise_and(img_2, img_2, mask=mask)

dst = cv2.add(img1_bg, img2_fg)
img_1[0:rows, 0:cols] = dst

cv2.imshow('res', img_1)
cv2.imshow('mask_inv', mask_inv)
cv2.imshow('img1 bg', img1_bg)
cv2.imshow('img2 fg', img2_fg)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()